export let cardData=[
    {   
        id:1,
        company_img:"/images/iUSD_token.png",
        company_name:"BUSD",
        company_desc:"on Trader Joe",
        month_percent:"0.0%",
        month:"APR",
        tvl_dollar:"$0.00",
        tvl:"TVL",
        company_deposit:"0.00 BUSD",
        deposit:"Your Deposits",
        dollar_reward:"$0.00",
        reward:"Rewards",
        category:"Main Pool",
        bgColor:"oddCardBgColor"
    },
    { 
        id:2,
        company_img:"/images/iUSD_token.png",
        company_name:"BUSD",
        company_desc:"on Trader Joe",
        month_percent:"0.0%",
        month:"APR",
        tvl_dollar:"$0.00",
        tvl:"TVL",
        company_deposit:"0.00 BUSD",
        deposit:"Your Deposits",
        dollar_reward:"$0.00",
        reward:"Rewards",
        category:"Main Pool",
        bgColor:"evenCardBgColor"
    },
    { 
        id:3,
        company_img:"/images/iUSD_token.png",
        company_name:"BUSD",
        company_desc:"on Trader Joe",
        month_percent:"0.0%",
        month:"APR",
        tvl_dollar:"$0.00",
        tvl:"TVL",
        company_deposit:"0.00 BUSD",
        deposit:"Your Deposits",
        dollar_reward:"$0.00",
        reward:"Rewards",
        category:"Main Pool",
        bgColor:"oddCardBgColor"
    },
    { 
        id:4,
        company_img:"/images/iUSD_token.png",
        company_name:"BUSD",
        company_desc:"on Trader Joe",
        month_percent:"0.0%",
        month:"APR",
        tvl_dollar:"$0.00",
        tvl:"TVL",
        company_deposit:"0.00 BUSD",
        deposit:"Your Deposits",
        dollar_reward:"$0.00",
        reward:"Rewards",
        category:"Side Pool",
        bgColor:"evenCardBgColor"
    },
    // { 
    //     id:5,
    //     company_img:"/images/iUSD_token.png",
    //     company_name:"BUSD",
    //     company_desc:"on Trader Joe",
    //     month_percent:"0.0%",
    //     month:"APR",
    //     tvl_dollar:"$0.00",
    //     tvl:"TVL",
    //     company_deposit:"0.00 BUSD",
    //     deposit:"Your Deposits",
    //     dollar_reward:"$0.00",
    //     reward:"Rewards",
    //     category:"Side Pool",
    //     bgColor:"oddCardBgColor"
    // },
    // { 
    //     id:6,
    //     company_img:"/images/iUSD_token.png",
    //     company_name:"BUSD",
    //     company_desc:"on Trader Joe",
    //     month_percent:"0.0%",
    //     month:"APR",
    //     tvl_dollar:"$0.00",
    //     tvl:"TVL",
    //     company_deposit:"0.00 BUSD",
    //     deposit:"Your Deposits",
    //     dollar_reward:"$0.00",
    //     reward:"Rewards",
    //     category:"BNB Pools",
    //     bgColor:"evenCardBgColor"
    // },
    // { 
    //     id:7,
    //     company_img:"/images/iUSD_token.png",
    //     company_name:"BUSD",
    //     company_desc:"on Trader Joe",
    //     month_percent:"0.0%",
    //     month:"APR",
    //     tvl_dollar:"$0.00",
    //     tvl:"TVL",
    //     company_deposit:"0.00 BUSD",
    //     deposit:"Your Deposits",
    //     dollar_reward:"$0.00",
    //     reward:"Rewards",
    //     category:"Side Pool",
    //     bgColor:"oddCardBgColor"
    // },
    // { 
    //     id:8,
    //     company_img:"/images/iUSD_token.png",
    //     company_name:"BUSD",
    //     company_desc:"on Trader Joe",
    //     month_percent:"0.0%",
    //     month:"APR",
    //     tvl_dollar:"$0.00",
    //     tvl:"TVL",
    //     company_deposit:"0.00 BUSD",
    //     deposit:"Your Deposits",
    //     dollar_reward:"$0.00",
    //     reward:"Rewards",
    //     category:"BNB Pools",
    //     bgColor:"evenCardBgColor"
    // },
    // { 
    //     id:9,
    //     company_img:"/images/iUSD_token.png",
    //     company_name:"BUSD",
    //     company_desc:"on Trader Joe",
    //     month_percent:"0.0%",
    //     month:"APR",
    //     tvl_dollar:"$0.00",
    //     tvl:"TVL",
    //     company_deposit:"0.00 BUSD",
    //     deposit:"Your Deposits",
    //     dollar_reward:"$0.00",
    //     reward:"Rewards",
    //     category:"Magpie LP",
    //     bgColor:"oddCardBgColor"
    // },
    // { 
    //     id:10,
    //     company_img:"/images/iUSD_token.png",
    //     company_name:"BUSD",
    //     company_desc:"on Trader Joe",
    //     month_percent:"0.0%",
    //     month:"APR",
    //     tvl_dollar:"$0.00",
    //     tvl:"TVL",
    //     company_deposit:"0.00 BUSD",
    //     deposit:"Your Deposits",
    //     dollar_reward:"$0.00",
    //     reward:"Rewards",
    //     category:"Magpie LP",
    //     bgColor:"evenCardBgColor"
    // },
    
]